### ISSUE TITLE
Remove "With" from function signatures

### ISSUE THREAD

**Issue by benpate** [BrandonRomano/wrecker#18]
We can save a bunch of repeated typing by removing "With" from the beginning of most function calls.  For example: WithParam(), WithBody(), WithHeader().

This should be a simple search/replace.

**Comment by BrandonRomano** [comment]
Hey Ben,

I think this probably should be the way to go.

I initially went with `With` because it made the request feel more like a sentence, but without `With` still feels good, and saves on typing.

We should also add a note in the README that this project is under early dev and should expect breaking changes.

**Comment by benpate** [comment]
Just posted a new branch for this.  I'll make it a pull request once we have the WithBody() thing worked out.
